### ISSUE TITLE
[Feature request] Consistent color variations

### ISSUE THREAD

**Issue by vatterspun** [ator-dev/mark-my-search#1]
Big fan of what the program is doing, had a suggestion that I thought might help out.  Please close it if not.

**Current behavior**

Various websites seem to show different color variations for unclear reasons.  Search words up at the top have a grayish tint that looks great on dark mode website, but looks a bit flat and dull on white backgrounds.  Also, some results seem to carry different highlighting (pictured below)

![image](https://user-images.githubusercontent.com/1289134/174458745-21406431-3cd4-4cbe-8d78-b00743d95f96.png)

Tested on Firefox v101.0.1

**Requested behavior**

As much as possible, color consistency.  Because different sites can have color fonts, always having the correct color highlight is probably a tall order  However, having colors that are as much as possible the same in the header and results view should make analysis easier.

**Comment by ator-dev** [comment]
Thank you very much for your interest and posting the first issue! This means a lot to me (:

Highlights are partially transparent to try to make them a bit prettier (in some cases). It looks like on Reddit the exact string match of your search is automatically given a white background, so this shows through a bit and makes the highlighting look weird.

Personally I'm not too sure about the style of the highlights, and they haven't really changed since the first version (except to change the default colours). For example, should they have no transparency or have less on light-background sites, should the font colour/style be adjusted for better visibility, and should highlights be forced into a particular background size or style like with rounded corners? (In case you haven't noticed, the background can vary a lot across sites although the colour is always the same.)

If you have any thoughts on this that would be really helpful, and I'll try some things out when I've got the chance as well.

**Comment by vatterspun** [comment]
I gave this some more thought and I think the color similarity isn't going to be crucial to operations until you get into the 20+ search terms.  Here's a look at PDFXChange with similar functionality.  

![image](https://user-images.githubusercontent.com/1289134/174463769-4d5e8b1d-d43d-4b29-8452-defd1304a8b5.png)

Seeing these color highlights lets me see variety and duplication, which is one of the reasons I'm keen on software like Mark My Search.  (I realize that's not the primary use case.)

**Comment by ator-dev** [comment]
I think I've seen PDFXChange's feature mentioned before, and I really like the clarity (and of course consistency) shown in your screenshot. Forcing the height of highlight backgrounds to be the same is probably dangerous in case of disrupting the page layout, but subtle borders and corners would work well without any conflicts. Currently there are only 7 colours before they are repeated which isn't great, so perhaps styles like gradients or stripes could be added for large numbers of search terms?

> seeing these color highlights lets me see variety and duplication

Actually this was one of the main use cases I had in mind, and of course there are many possible others that I might not have considered. Definitely a priority is seeing how usage varies across a page at a glance (e.g. to see where is most useful or if the page is not relevant enough), which is why I'm looking to put a lot more work into the scrollbar view where overlapping markers currently hide each other.

**Comment by ator-dev** [comment]
Just to let you know by the way, I won't be working on this for about 2 weeks because of exams, which is also why progress has slowed down lately. I'm very interested in continuing to refine and support the project in my free time though, so feedback like this is invaluable.

**Comment by vatterspun** [comment]
> slowed down lately

Hey thanks for the update, no worries.

**Comment by ator-dev** [comment]
@vatterspun I have just updated Mark My Search on the Firefox listing with version 1.1.2 which implements many of the discussed features. When you have the time, would you mind trying it out please to check if your problems in this issue were addressed?

Changes from this issue:
* Slight transparency and more saturation for term buttons in order to improve their look on dark- and light-themed websites alike
* Enhance highlights style for better readability, taking inspiration from PDFXChange
* A secondary striped style for highlights has been added, doubling the number of unique highlights from 7 to 14

I have not made the extension work to detect a dark or light theme, but tried to make the style more dynamic so that it works in a wider variety of cases. This is to retain consistency as much as possible. The new highlight borders give distinction on light backgrounds but don't show up much on dark ones, which is also where they are less needed as the colours stand out anyway.

**Comment by vatterspun** [comment]
I tested on Firefox 103.0 and had great results.

> Slight transparency / Enhanced highlight style

Both of those changes look great -- well done

> A secondary striped style for highlights has been added, doubling the number of unique highlights from 7 to 14

I will say that the striped style definitely works and it calls out the colors, but it does diminish readability somewhat.  Maybe if they were a little dimmer?

![image](https://user-images.githubusercontent.com/1289134/182061202-887bcad4-9822-4369-b1ee-42abffa55fb9.png)

>tried to make the style more dynamic so that it works in a wider variety of cases.

I tested with DuckDuckGo dark mode it looks great:

![image](https://user-images.githubusercontent.com/1289134/182061695-c29fc829-5a4e-4c9f-9003-2a1312dc9038.png)

**Comment by ator-dev** [comment]
Thank you again for testing! I'm pleased it was what you had in mind and improved the experience.

> Maybe if they were a little dimmer?

I agree with this, they're often a bit hard to read - I'll try dimming them as well as other adjustments. I'll also get around to adding a tertiary style (probably just stripes in the other direction) and maybe other options.

I also notice from your screenshots that the re-search icon (second from the left) has turned into an ugly circle, which is because my implementation only works well with my specific font (oops). This will be replaced with an SVG.

**Comment by vatterspun** [comment]
> I agree with this, they're often a bit hard to read - I'll try dimming them as well as other adjustments

Sounds good, I'll leave this issue open for the time being.  Or however you prefer to manage your Github issues.

> ... the re-search icon (second from the left) has turned into an ugly circle, which is because my implementation only works well with my specific font (oops). This will be replaced with an SVG.

Excellent, glad I included that.

**Comment by vatterspun** [comment]
Sidenote: it didn't escape my notice that the gray box appears for terms that don't actually show up in the document below.  I thought this was a bug until I played around with it.

![image](https://user-images.githubusercontent.com/1289134/182229052-a5291684-151f-4f18-b15a-7a5d4417ab40.png)

**Comment by ator-dev** [comment]
Sorry for not responding to your recent comments. I immediately started working on some enhancements based on your feedback, and it took longer than expected since I got caught up in fixing other features.

The striped style has (hopefully) been improved, and there are now several rotations in case the user wants 35 terms for some reason. All icons are now SVGs, scaling works properly, and UI style has been adjusted for consistency - this should mean that the extension looks great on any platform.

> I thought this was a bug until I played around with it.
> Great add.

Thank you, glad it's useful! I'm closing this issue for now because I don't know how to make its intention clear, but feel free to reopen if you think it needs fixing (alternatively, could be included in the intro / onboarding?)
